In [58]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity
movies_df = pd.read_csv(r"C:\Users\Abdelrahman Muhsen\Desktop\ASS7AI\ContentBasedRecommenderSystem\movies.csv")
ratings_df = pd.read_csv(r"C:\Users\Abdelrahman Muhsen\Desktop\ASS7AI\ContentBasedRecommenderSystem\ratings.csv")


In [59]:
data=ratings_df[ratings_df.userId<=200]
data = data.drop(['timestamp'], axis=1)
data =data.groupby(['userId', 'movieId']).sum().reset_index().pivot(index='movieId', columns='userId').fillna(0)
data=data.iloc[0:200 ,0:200]

print(data)

        rating                                               ...            \
userId     1    2    3    4    5    6    7    8    9    10   ...  191  192   
movieId                                                      ...             
1          4.0  0.0  0.0  0.0  4.0  0.0  4.5  0.0  0.0  0.0  ...  4.0  0.0   
2          0.0  0.0  0.0  0.0  0.0  4.0  0.0  4.0  0.0  0.0  ...  0.0  0.0   
3          4.0  0.0  0.0  0.0  0.0  5.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
4          0.0  0.0  0.0  0.0  0.0  3.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
5          0.0  0.0  0.0  0.0  0.0  5.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
...        ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
256        0.0  0.0  0.0  0.0  0.0  3.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
257        0.0  0.0  0.0  0.0  0.0  5.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
258        0.0  0.0  0.0  0.0  0.0  3.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
259        0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...

In [60]:

cosine_sim = cosine_similarity(data)
print(cosine_sim)


[[1.         0.36463355 0.28482541 ... 0.1442169  0.12188553 0.53314711]
 [0.36463355 1.         0.27844551 ... 0.39148941 0.         0.37467155]
 [0.28482541 0.27844551 1.         ... 0.24385598 0.24044524 0.21150086]
 ...
 [0.1442169  0.39148941 0.24385598 ... 1.         0.         0.15974675]
 [0.12188553 0.         0.24044524 ... 0.         1.         0.        ]
 [0.53314711 0.37467155 0.21150086 ... 0.15974675 0.         1.        ]]


In [61]:
def gettitle(id):
    return movies[movies.movieId ==id]["title"].values

def recommender(movie_idx):
    movietitle=gettitle(movie_idx)
    print("movei to get matches to",movietitle)
    similar_movies = list(enumerate(cosine_sim[movie_idx]))
    sorted_similar_movies = sorted(similar_movies, key=lambda x:x[1], reverse=True)
    i=1
    for movie in sorted_similar_movies[1:]:
        recommmended=gettitle(movie[0])
        if(recommmended.size>0):
            print(recommmended)
            i=i+1
        if i>10:
            break
    return

In [62]:
recommender(1)

movei to get matches to ['Toy Story (1995)']
['Rumble in the Bronx (Hont faan kui) (1995)']
['Dangerous Minds (1995)']
['When Night Is Falling (1995)']
['White Squall (1996)']
['Batman Forever (1995)']
['Down Periscope (1996)']
["Antonia's Line (Antonia) (1995)"]
['Umbrellas of Cherbourg, The (Parapluies de Cherbourg, Les) (1964)']
['Richard III (1995)']
['Judge Dredd (1995)']


In [63]:
recommender(4)

movei to get matches to ['Waiting to Exhale (1995)']
['Heat (1995)']
['Bio-Dome (1996)']
['Party Girl (1995)']
['Crumb (1994)']
['GoldenEye (1995)']
['Heidi Fleiss: Hollywood Madam (1995)']
['Sabrina (1995)']
['When Night Is Falling (1995)']
['Richard III (1995)']
['Jumanji (1995)']


In [64]:
#recommend based on genres
movies=movies_df[movies_df.movieId <=200]
features = 'genres'
cv = CountVectorizer()
count_matrix = cv.fit_transform(movies[features])
cosine_sim = cosine_similarity(count_matrix)
def reommendbasedongenres(movie_idx):
    movietitle=gettitle(movie_idx)
    print("movei to get matches to",movietitle)
    similar_movies = list(enumerate(cosine_sim[movie_idx]))
    sorted_similar_movies = sorted(similar_movies, key=lambda x:x[1], reverse=True)
    i=1
    print("sorted_similar_movies")
    for movie in sorted_similar_movies[1:]:
        recommmended=gettitle(movie[0])
        if(recommmended.size>0):
            print(recommmended)
            i=i+1
        if i>10:
            break
    return

In [65]:
reommendbasedongenres(1)

movei to get matches to ['Toy Story (1995)']
sorted_similar_movies
['Lamerica (1994)']
['Sabrina (1995)']
['Steal Big, Steal Little (1995)']
['Dracula: Dead and Loving It (1995)']
['Cry, the Beloved Country (1995)']
['Birdcage, The (1996)']
['Broken Arrow (1996)']
['Persuasion (1995)']
['Othello (1995)']
['Twelve Monkeys (a.k.a. 12 Monkeys) (1995)']


In [66]:
reommendbasedongenres(4)

movei to get matches to ['Waiting to Exhale (1995)']
sorted_similar_movies
['Sense and Sensibility (1995)']
['Four Rooms (1995)']
['Postman, The (Postino, Il) (1994)']
['Eye for an Eye (1996)']
['Juror, The (1996)']
['Mary Reilly (1996)']
['Happy Gilmore (1996)']
['Catwalk (1996)']
['Before and After (1996)']
['Anne Frank Remembered (1995)']
